/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import view.GUITableroJuego;
/**
 *
 * @author Yoel Gonzalez
 */
public class GUIInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreditos = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnComb = new javax.swing.JComboBox<>();
        btnInicio = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreditos.setBackground(new java.awt.Color(0, 0, 153));
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Creditos");
        jPanel1.add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        btnHistoria.setBackground(new java.awt.Color(0, 0, 153));
        btnHistoria.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoria.setText("Historia");
        jPanel1.add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        btnInstrucciones.setBackground(new java.awt.Color(0, 0, 153));
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        jPanel1.add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        btnComb.setBackground(new java.awt.Color(0, 0, 153));
        btnComb.setForeground(new java.awt.Color(255, 255, 255));
        btnComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Azul", "Verde" }));
        btnComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombActionPerformed(evt);
            }
        });
        jPanel1.add(btnComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 240, 100));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgInicio_1.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        GUITableroJuego tablero = new GUITableroJuego();
        tablero.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btnComb;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
