/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author Yoel Gonzalez
 */
public class PanelTableroF extends javax.swing.JPanel {

    /**
     * Creates new form PanelTableroF
     */
    public PanelTableroF() {
        
        this.addMouseListener(new MouseAdapter(){
        
            public void mousePressed(MouseEvent e){
            Point p = e.getPoint();
            MoverFicha(p);
            MoverFichaR(p);
            }
        
        });

        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFichaR1 = new javax.swing.JLabel();
        lblFichaA1 = new javax.swing.JLabel();
        lblTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFichaR1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yoel Gonzalez\\Documents\\Assets de Parchís\\Ficha Roja.png")); // NOI18N
        add(lblFichaR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 20, -1));

        lblFichaA1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yoel Gonzalez\\Documents\\Assets de Parchís\\Ficha Amarilla.png")); // NOI18N
        add(lblFichaA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lblTablero.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yoel Gonzalez\\Documents\\Assets de Parchís\\TTAPPAA.png")); // NOI18N
        add(lblTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 550));
    }// </editor-fold>//GEN-END:initComponents
    public void MoverFicha(Point p){
    
        lblFichaA1.setLocation(p);
        System.out.println("Coordenadas "+p.x+" "+p.y);
    
    }
    public void MoverFichaR(Point p){
    
        lblFichaR1.setLocation(p);
        System.out.println("Coordenadas "+p.x+" "+p.y);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFichaA1;
    private javax.swing.JLabel lblFichaR1;
    private javax.swing.JLabel lblTablero;
    // End of variables declaration//GEN-END:variables
}
